(ag_percept (percept_pobj car_opp) (percept_pname isa) (percept_pval car))
(ag_percept (percept_pobj car_opp) (percept_pname rel_pos) (percept_pval front_contrasens))
(ag_percept (percept_pobj line1) (percept_pname isa) (percept_pval line))
(ag_percept (percept_pobj line1) (percept_pname type) (percept_pval broken_line))
(ag_percept (percept_pobj my_car) (percept_pname isa) (percept_pval car))
