(ag_percept (percept_pobj my_car) (percept_pname isa) (percept_pval car))
(ag_percept (percept_pobj my_car) (percept_pname signal) (percept_pval left))
(ag_percept (percept_pobj my_car) (percept_pname speed) (percept_pval 60))
(ag_percept (percept_pobj tractor1) (percept_pname isa) (percept_pval vehicle))
(ag_percept (percept_pobj line1) (percept_pname isa) (percept_pval line))
(ag_percept (percept_pobj line1) (percept_pname type) (percept_pval broken_line))
