(ag_percept (percept_pobj my_car) (percept_pname isa) (percept_pval car))
(ag_percept (percept_pobj my_car) (percept_pname signal) (percept_pval right))
(ag_percept (percept_pobj tractor1) (percept_pname isa) (percept_pval vehicle))
(ag_percept (percept_pobj tractor1) (percept_pname rel_pos) (percept_pval back))
(ag_percept (percept_pobj line1) (percept_pname isa) (percept_pval line))
(ag_percept (percept_pobj line1) (percept_pname type) (percept_pval broken_line))
