(ag_percept (percept_pobj sign_no_overtaking) (percept_pname isa) (percept_pval road_sign))
(ag_percept (percept_pobj sign_no_overtaking) (percept_pname type) (percept_pval overtaking_prohibited))
(ag_percept (percept_pobj line1) (percept_pname isa) (percept_pval line))
(ag_percept (percept_pobj line1) (percept_pname type) (percept_pval continuous_line))
(ag_percept (percept_pobj my_car) (percept_pname isa) (percept_pval car))
