(ag_percept (percept_pobj road1) (percept_pname isa) (percept_pval road))
(ag_percept (percept_pobj road1) (percept_pname road_location) (percept_pval national_road))
(ag_percept (percept_pobj sign1) (percept_pname isa) (percept_pval road_sign))
(ag_percept (percept_pobj sign1) (percept_pname type) (percept_pval overtaking_prohibited))
(ag_percept (percept_pobj line1) (percept_pname isa) (percept_pval line))
(ag_percept (percept_pobj line1) (percept_pname type) (percept_pval broken_line))
(ag_percept (percept_pobj my_car) (percept_pname isa) (percept_pval car))
(ag_percept (percept_pobj my_car) (percept_pname speed) (percept_pval 80))