(ag_percept (percept_pobj sign3) (percept_pname isa) (percept_pval road_sign))
(ag_percept (percept_pobj sign3) (percept_pname type) (percept_pval end_of_overtaking_prohibition))
(ag_percept (percept_pobj line1) (percept_pname isa) (percept_pval line))
(ag_percept (percept_pobj line1) (percept_pname type) (percept_pval continuous_line))
(ag_percept (percept_pobj my_car) (percept_pname isa) (percept_pval car))
(ag_percept (percept_pobj my_car) (percept_pname speed) (percept_pval 60))