(ag_percept (percept_pobj my_car) (percept_pname isa) (percept_pval car))
(ag_percept (percept_pobj my_car) (percept_pname speed) (percept_pval 80))
(ag_percept (percept_pobj my_car) (percept_pname position) (percept_pval contrasens))
(ag_percept (percept_pobj truck1) (percept_pname isa) (percept_pval vehicle))
(ag_percept (percept_pobj truck1) (percept_pname rel_dist) (percept_pval 0))
(ag_percept (percept_pobj truck1) (percept_pname rel_pos) (percept_pval lateral_right))
(ag_percept (percept_pobj line1) (percept_pname isa) (percept_pval line))
(ag_percept (percept_pobj line1) (percept_pname type) (percept_pval broken_line))