(ag_percept (percept_pobj car_emergency) (percept_pname isa) (percept_pval car))
(ag_percept (percept_pobj car_emergency) (percept_pname lane) (percept_pval emergency_lane))
(ag_percept (percept_pobj car_emergency) (percept_pname lights) (percept_pval hazard_lights_on))
(ag_percept (percept_pobj line1) (percept_pname isa) (percept_pval line))
(ag_percept (percept_pobj line1) (percept_pname type) (percept_pval broken_line))
(ag_percept (percept_pobj my_car) (percept_pname isa) (percept_pval car))