(ag_percept (percept_pobj road1) (percept_pname isa) (percept_pval road))
(ag_percept (percept_pobj road1) (percept_pname weather) (percept_pval strong_side_wind))
(ag_percept (percept_pobj truck2) (percept_pname isa) (percept_pval vehicle))
(ag_percept (percept_pobj truck2) (percept_pname rel_pos) (percept_pval lateral_right))
(ag_percept (percept_pobj line1) (percept_pname isa) (percept_pval line))
(ag_percept (percept_pobj line1) (percept_pname type) (percept_pval broken_line))