(ag_percept (percept_pobj my_car) (percept_pname isa) (percept_pval car))
(ag_percept (percept_pobj my_car) (percept_pname speed) (percept_pval 130))
(ag_percept (percept_pobj truck2) (percept_pname isa) (percept_pval vehicle))
(ag_percept (percept_pobj truck2) (percept_pname rel_dist) (percept_pval -100))
(ag_percept (percept_pobj line1) (percept_pname isa) (percept_pval line))
(ag_percept (percept_pobj line1) (percept_pname type) (percept_pval broken_line))