(ag_percept (percept_pobj sign_exit) (percept_pname isa) (percept_pval road_sign))
(ag_percept (percept_pobj sign_exit) (percept_pname type) (percept_pval exit_at_1000m))
(ag_percept (percept_pobj line1) (percept_pname isa) (percept_pval line))
(ag_percept (percept_pobj line1) (percept_pname type) (percept_pval broken_line))
(ag_percept (percept_pobj my_car) (percept_pname isa) (percept_pval car))
(ag_percept (percept_pobj my_car) (percept_pname speed) (percept_pval 120))