(ag_percept (percept_pobj car_slow) (percept_pname isa) (percept_pval car))
(ag_percept (percept_pobj car_slow) (percept_pname rel_dist) (percept_pval 200))
(ag_percept (percept_pobj car_slow) (percept_pname has_speed) (percept_pval 100))
(ag_percept (percept_pobj line1) (percept_pname isa) (percept_pval line))
(ag_percept (percept_pobj line1) (percept_pname type) (percept_pval broken_line))
(ag_percept (percept_pobj my_car) (percept_pname isa) (percept_pval car))