(ag_percept (percept_pobj tram1) (percept_pname isa) (percept_pval tram))
(ag_percept (percept_pobj tram1) (percept_pname status) (percept_pval boarding_passengers))
(ag_percept (percept_pobj line1) (percept_pname isa) (percept_pval line))
(ag_percept (percept_pobj line1) (percept_pname type) (percept_pval continuous_line))
(ag_percept (percept_pobj my_car) (percept_pname isa) (percept_pval car))
(ag_percept (percept_pobj my_car) (percept_pname speed) (percept_pval 0))