(ag_percept (percept_pobj cyclist1) (percept_pname isa) (percept_pval cyclist))
(ag_percept (percept_pobj cyclist1) (percept_pname rel_dist) (percept_pval 50))
(ag_percept (percept_pobj line1) (percept_pname isa) (percept_pval line))
(ag_percept (percept_pobj line1) (percept_pname type) (percept_pval continuous_line))
(ag_percept (percept_pobj my_car) (percept_pname isa) (percept_pval car))
(ag_percept (percept_pobj my_car) (percept_pname speed) (percept_pval 40))