(ag_percept (percept_pobj sign_no_left) (percept_pname isa) (percept_pval road_sign))
(ag_percept (percept_pobj sign_no_left) (percept_pname type) (percept_pval no_left_turn))
(ag_percept (percept_pobj line1) (percept_pname isa) (percept_pval line))
(ag_percept (percept_pobj line1) (percept_pname type) (percept_pval continuous_line))
(ag_percept (percept_pobj my_car) (percept_pname isa) (percept_pval car))
(ag_percept (percept_pobj my_car) (percept_pname speed) (percept_pval 45))