(ag_percept (percept_pobj ambulance1) (percept_pname isa) (percept_pval emergency_vehicle))
(ag_percept (percept_pobj ambulance1) (percept_pname status) (percept_pval approaching_from_back))
(ag_percept (percept_pobj line1) (percept_pname isa) (percept_pval line))
(ag_percept (percept_pobj line1) (percept_pname type) (percept_pval broken_line))
(ag_percept (percept_pobj my_car) (percept_pname isa) (percept_pval car))
(ag_percept (percept_pobj my_car) (percept_pname action) (percept_pval pulling_over))