(ag_percept (percept_pobj pedestrian1) (percept_pname isa) (percept_pval pedestrian))
(ag_percept (percept_pobj pedestrian1) (percept_pname action) (percept_pval crossing))
(ag_percept (percept_pobj line1) (percept_pname isa) (percept_pval line))
(ag_percept (percept_pobj line1) (percept_pname type) (percept_pval broken_line))
(ag_percept (percept_pobj my_car) (percept_pname isa) (percept_pval car))
(ag_percept (percept_pobj my_car) (percept_pname speed) (percept_pval 20))