(ag_percept (percept_pobj traffic_light1) (percept_pname isa) (percept_pval traffic_light))
(ag_percept (percept_pobj traffic_light1) (percept_pname color) (percept_pval green))
(ag_percept (percept_pobj line1) (percept_pname isa) (percept_pval line))
(ag_percept (percept_pobj line1) (percept_pname type) (percept_pval continuous_line))
(ag_percept (percept_pobj my_car) (percept_pname isa) (percept_pval car))
(ag_percept (percept_pobj my_car) (percept_pname speed) (percept_pval 45))