(ag_percept (percept_pobj road1) (percept_pname isa) (percept_pval road))
(ag_percept (percept_pobj road1) (percept_pname infrastructure) (percept_pval tram_stop_no_refuge))
(ag_percept (percept_pobj tram1) (percept_pname isa) (percept_pval tram))
(ag_percept (percept_pobj tram1) (percept_pname rel_dist) (percept_pval 60))
(ag_percept (percept_pobj line1) (percept_pname isa) (percept_pval line))
(ag_percept (percept_pobj line1) (percept_pname type) (percept_pval broken_line))